--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Cryptos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cryptos" (
    "IdCrypto" integer NOT NULL,
    "Symbole" text NOT NULL,
    "Nom" text NOT NULL
);


ALTER TABLE public."Cryptos" OWNER TO postgres;

--
-- Name: Cryptos_IdCrypto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cryptos" ALTER COLUMN "IdCrypto" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cryptos_IdCrypto_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Favoris; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Favoris" (
    "idUser" integer NOT NULL,
    "idCrypto" integer NOT NULL,
    "IdFavoris" integer NOT NULL
);


ALTER TABLE public."Favoris" OWNER TO postgres;

--
-- Name: Historiques; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Historiques" (
    "IdHistorique" integer NOT NULL,
    "PrixCrypto" double precision NOT NULL,
    "DateChange" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "idCrypto" integer NOT NULL
);


ALTER TABLE public."Historiques" OWNER TO postgres;

--
-- Name: Historiques_IdHistorique_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Historiques" ALTER COLUMN "IdHistorique" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Historiques_IdHistorique_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Ordres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ordres" (
    "IdOrdre" integer NOT NULL,
    "PrixUnitaire" double precision NOT NULL,
    "AmountCrypto" double precision NOT NULL,
    "IdTransaction" integer,
    "IdCrypto" integer NOT NULL
);


ALTER TABLE public."Ordres" OWNER TO postgres;

--
-- Name: Ordres_IdOrdre_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Ordres" ALTER COLUMN "IdOrdre" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ordres_IdOrdre_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Portefeuilles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Portefeuilles" (
    "IdPortefeuille" integer NOT NULL,
    "IdUser" integer NOT NULL,
    "Fond" double precision NOT NULL
);


ALTER TABLE public."Portefeuilles" OWNER TO postgres;

--
-- Name: Portefeuilles_IdPortefeuille_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Portefeuilles" ALTER COLUMN "IdPortefeuille" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Portefeuilles_IdPortefeuille_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Stocks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Stocks" (
    "IdPorteFeuille" integer NOT NULL,
    "IdCrypto" integer NOT NULL,
    "IdStock" integer NOT NULL,
    "Stock" double precision NOT NULL
);


ALTER TABLE public."Stocks" OWNER TO postgres;

--
-- Name: Tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tokens" (
    "IdToken" integer NOT NULL,
    "Token" text NOT NULL,
    "DateExpiration" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "IdTransaction" integer NOT NULL
);


ALTER TABLE public."Tokens" OWNER TO postgres;

--
-- Name: Tokens_IdToken_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tokens" ALTER COLUMN "IdToken" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tokens_IdToken_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Transac; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Transac" (
    "IdTransaction" integer NOT NULL,
    "Type" integer NOT NULL,
    "State" integer NOT NULL,
    "DateTransaction" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "IdPortefeuille" integer NOT NULL,
    fond double precision NOT NULL
);


ALTER TABLE public."Transac" OWNER TO postgres;

--
-- Name: Transac_IdTransaction_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Transac" ALTER COLUMN "IdTransaction" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transac_IdTransaction_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Cryptos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Cryptos" ("IdCrypto", "Symbole", "Nom") FROM stdin;
\.


--
-- Data for Name: Favoris; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Favoris" ("idUser", "idCrypto", "IdFavoris") FROM stdin;
\.


--
-- Data for Name: Historiques; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Historiques" ("IdHistorique", "PrixCrypto", "DateChange", "idCrypto") FROM stdin;
\.


--
-- Data for Name: Ordres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Ordres" ("IdOrdre", "PrixUnitaire", "AmountCrypto", "IdTransaction", "IdCrypto") FROM stdin;
\.


--
-- Data for Name: Portefeuilles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Portefeuilles" ("IdPortefeuille", "IdUser", "Fond") FROM stdin;
\.


--
-- Data for Name: Stocks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Stocks" ("IdPorteFeuille", "IdCrypto", "IdStock", "Stock") FROM stdin;
\.


--
-- Data for Name: Tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tokens" ("IdToken", "Token", "DateExpiration", "IsUsed", "IdTransaction") FROM stdin;
\.


--
-- Data for Name: Transac; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Transac" ("IdTransaction", "Type", "State", "DateTransaction", "IdPortefeuille", fond) FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250207063716_InitialMigration	9.0.0
\.


--
-- Name: Cryptos_IdCrypto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Cryptos_IdCrypto_seq"', 1, false);


--
-- Name: Historiques_IdHistorique_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Historiques_IdHistorique_seq"', 1, false);


--
-- Name: Ordres_IdOrdre_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Ordres_IdOrdre_seq"', 1, false);


--
-- Name: Portefeuilles_IdPortefeuille_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Portefeuilles_IdPortefeuille_seq"', 1, false);


--
-- Name: Tokens_IdToken_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tokens_IdToken_seq"', 1, false);


--
-- Name: Transac_IdTransaction_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Transac_IdTransaction_seq"', 1, false);


--
-- Name: Cryptos PK_Cryptos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cryptos"
    ADD CONSTRAINT "PK_Cryptos" PRIMARY KEY ("IdCrypto");


--
-- Name: Favoris PK_Favoris; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favoris"
    ADD CONSTRAINT "PK_Favoris" PRIMARY KEY ("idCrypto", "idUser");


--
-- Name: Historiques PK_Historiques; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Historiques"
    ADD CONSTRAINT "PK_Historiques" PRIMARY KEY ("IdHistorique");


--
-- Name: Ordres PK_Ordres; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ordres"
    ADD CONSTRAINT "PK_Ordres" PRIMARY KEY ("IdOrdre");


--
-- Name: Portefeuilles PK_Portefeuilles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Portefeuilles"
    ADD CONSTRAINT "PK_Portefeuilles" PRIMARY KEY ("IdPortefeuille");


--
-- Name: Stocks PK_Stocks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Stocks"
    ADD CONSTRAINT "PK_Stocks" PRIMARY KEY ("IdPorteFeuille", "IdCrypto");


--
-- Name: Tokens PK_Tokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tokens"
    ADD CONSTRAINT "PK_Tokens" PRIMARY KEY ("IdToken");


--
-- Name: Transac PK_Transac; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transac"
    ADD CONSTRAINT "PK_Transac" PRIMARY KEY ("IdTransaction");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Cryptos_Nom; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Cryptos_Nom" ON public."Cryptos" USING btree ("Nom");


--
-- Name: IX_Cryptos_Symbole; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Cryptos_Symbole" ON public."Cryptos" USING btree ("Symbole");


--
-- Name: IX_Historiques_idCrypto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Historiques_idCrypto" ON public."Historiques" USING btree ("idCrypto");


--
-- Name: IX_Ordres_IdCrypto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Ordres_IdCrypto" ON public."Ordres" USING btree ("IdCrypto");


--
-- Name: IX_Ordres_IdTransaction; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Ordres_IdTransaction" ON public."Ordres" USING btree ("IdTransaction");


--
-- Name: IX_Portefeuilles_IdUser; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Portefeuilles_IdUser" ON public."Portefeuilles" USING btree ("IdUser");


--
-- Name: IX_Stocks_IdCrypto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Stocks_IdCrypto" ON public."Stocks" USING btree ("IdCrypto");


--
-- Name: IX_Tokens_IdTransaction; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tokens_IdTransaction" ON public."Tokens" USING btree ("IdTransaction");


--
-- Name: IX_Transac_IdPortefeuille; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transac_IdPortefeuille" ON public."Transac" USING btree ("IdPortefeuille");


--
-- Name: Favoris FK_Favoris_Cryptos_idCrypto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favoris"
    ADD CONSTRAINT "FK_Favoris_Cryptos_idCrypto" FOREIGN KEY ("idCrypto") REFERENCES public."Cryptos"("IdCrypto") ON DELETE CASCADE;


--
-- Name: Historiques FK_Historiques_Cryptos_idCrypto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Historiques"
    ADD CONSTRAINT "FK_Historiques_Cryptos_idCrypto" FOREIGN KEY ("idCrypto") REFERENCES public."Cryptos"("IdCrypto") ON DELETE CASCADE;


--
-- Name: Ordres FK_Ordres_Cryptos_IdCrypto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ordres"
    ADD CONSTRAINT "FK_Ordres_Cryptos_IdCrypto" FOREIGN KEY ("IdCrypto") REFERENCES public."Cryptos"("IdCrypto") ON DELETE CASCADE;


--
-- Name: Ordres FK_Ordres_Transac_IdTransaction; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ordres"
    ADD CONSTRAINT "FK_Ordres_Transac_IdTransaction" FOREIGN KEY ("IdTransaction") REFERENCES public."Transac"("IdTransaction") ON DELETE CASCADE;


--
-- Name: Stocks FK_Stocks_Cryptos_IdCrypto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Stocks"
    ADD CONSTRAINT "FK_Stocks_Cryptos_IdCrypto" FOREIGN KEY ("IdCrypto") REFERENCES public."Cryptos"("IdCrypto") ON DELETE CASCADE;


--
-- Name: Stocks FK_Stocks_Portefeuilles_IdPorteFeuille; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Stocks"
    ADD CONSTRAINT "FK_Stocks_Portefeuilles_IdPorteFeuille" FOREIGN KEY ("IdPorteFeuille") REFERENCES public."Portefeuilles"("IdPortefeuille") ON DELETE CASCADE;


--
-- Name: Tokens FK_Tokens_Transac_IdTransaction; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tokens"
    ADD CONSTRAINT "FK_Tokens_Transac_IdTransaction" FOREIGN KEY ("IdTransaction") REFERENCES public."Transac"("IdTransaction") ON DELETE CASCADE;


--
-- Name: Transac FK_Transac_Portefeuilles_IdPortefeuille; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transac"
    ADD CONSTRAINT "FK_Transac_Portefeuilles_IdPortefeuille" FOREIGN KEY ("IdPortefeuille") REFERENCES public."Portefeuilles"("IdPortefeuille") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

