version: '3.7'

services:
  backend_crypto-db:
    image: postgres:latest
    container_name: backend_crypto-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crypto_tp
    ports:
      - "5433:5432"
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend_crypto-api:
    build: .
    container_name: backend_crypto-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__PostgreSqlConnection=Host=backend_crypto-db;Port=5432;Username=postgres;Password=root;Database=crypto_tp
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - backend_crypto-db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
