nelmio_api_doc:
    documentation:
        info:
            title: TP CLOUD
            description: Application de dispatching d'identité
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
